# Machine Learning Pipeline
- Import the data
- Clean the data
- Split the data into traning set and test set
- Create a model (Choosing best fit algo)
- Train the model
- Make Predicition
- Evaluate the result and improve

In [1]:
import pandas as pd
movies_data = pd.read_csv('movies.csv')
movies_data

    age  gender        genre
0    20       1       Action
1    23       1       Action
2    25       1       Action
3    26       1       Sci-Fi
4    29       1       Sci-Fi
5    30       1       Sci-Fi
6    31       1        Drama
7    33       1        Drama
8    37       1        Drama
9    20       0       Comedy
10   21       0       Comedy
11   25       0       Comedy
12   26       0  Documentary
13   27       0  Documentary
14   30       0  Documentary
15   31       0        Drama
16   34       0        Drama
17   35       0        Drama

In [2]:
# Represents input data set (denoted by X)
X = movies_data.drop(columns=['genre'])
X

    age  gender
0    20       1
1    23       1
2    25       1
3    26       1
4    29       1
5    30       1
6    31       1
7    33       1
8    37       1
9    20       0
10   21       0
11   25       0
12   26       0
13   27       0
14   30       0
15   31       0
16   34       0
17   35       0

In [3]:
# Represents output data set (denoted by y)
y = movies_data['genre']
y

0          Action
1          Action
2          Action
3          Sci-Fi
4          Sci-Fi
5          Sci-Fi
6           Drama
7           Drama
8           Drama
9          Comedy
10         Comedy
11         Comedy
12    Documentary
13    Documentary
14    Documentary
15          Drama
16          Drama
17          Drama
Name: genre, dtype: object

In [4]:
X.values

array([[20,  1],
       [23,  1],
       [25,  1],
       [26,  1],
       [29,  1],
       [30,  1],
       [31,  1],
       [33,  1],
       [37,  1],
       [20,  0],
       [21,  0],
       [25,  0],
       [26,  0],
       [27,  0],
       [30,  0],
       [31,  0],
       [34,  0],
       [35,  0]])

In [5]:
y.values

array(['Action', 'Action', 'Action', 'Sci-Fi', 'Sci-Fi', 'Sci-Fi',
       'Drama', 'Drama', 'Drama', 'Comedy', 'Comedy', 'Comedy',
       'Documentary', 'Documentary', 'Documentary', 'Drama', 'Drama',
       'Drama'], dtype=object)

In [6]:
# Model creation
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X.values, y.values)

DecisionTreeClassifier()

In [7]:
movies_data

    age  gender        genre
0    20       1       Action
1    23       1       Action
2    25       1       Action
3    26       1       Sci-Fi
4    29       1       Sci-Fi
5    30       1       Sci-Fi
6    31       1        Drama
7    33       1        Drama
8    37       1        Drama
9    20       0       Comedy
10   21       0       Comedy
11   25       0       Comedy
12   26       0  Documentary
13   27       0  Documentary
14   30       0  Documentary
15   31       0        Drama
16   34       0        Drama
17   35       0        Drama

In [8]:
# Prediction
predictions = model.predict([[21, 1], [23, 0]])
predictions

array(['Action', 'Comedy'], dtype=object)

In [9]:
# Split training set and test set
from sklearn.model_selection import train_test_split

# More test data more accurate, changing test_size from 0.2 to 0.8 accuracy redued from 1.0 to 0.4
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(x_train.values, y_train.values)
predictions = model.predict(x_test.values)

In [10]:
# Accuracy eval (0-1)
from sklearn.metrics import accuracy_score

score = accuracy_score(y_test, predictions)
score

1.0

In [11]:
# Model persistance
import joblib

joblib.dump(model, 'movie-recommender.joblib')

['movie-recommender.joblib']

In [12]:
# Loading the model
trained_model = joblib.load('movie-recommender.joblib')

new_predictions = trained_model.predict([[29,0]])
new_predictions

array(['Documentary'], dtype=object)

In [13]:
# Visualizing how decision tree works
from sklearn import tree

tree.export_graphviz(trained_model, out_file='movies_recommender.dot',
                        feature_names=['age','gender'],
                        class_names=sorted(y.unique()),
                        label='all',
                        rounded=True,
                        filled=True
                    )